name: hyakunin_isshu
description: This library has been developed to make it easy to use Japanese Hyakunin Isshu in Dart and Flutter applications.
version: 1.2.0
homepage: https://github.com/hyakunin-isshu/hyakunin-isshu

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  collection: ^1.15.0
  http: ^0.13.4
  json_response: ^2.3.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  import_sorter: ^4.6.0
